### PR TITLE
Format backtrace tests

### PR DESCRIPTION
**Pull request by mistermuckle**
Moved `format_backtrace()` into a family of classes, added lots of c-tests, and replaced all uses of the function with OO calls.

### CODE REVIEW

**Comment by CarwynNelson** [comment]
Since these are meant to be characterisation tests it feels a bit wrong to me to do all of this extraction.

Surely the intention is to make as a few changes as possible?

I believe the function could be unit tested on its own.

**Comment by mistermuckle** [comment]
Essentially the original function code is in each of the two new classes, untouched. We need to be able to access the function in isolation & mock the directory dependency to test, hence the classes. 

I decided on two classes to simplify the logic for HTML vs plaintext, rather than having one class with lots of if/thens; I think that separation is trivial enough to warrant having done so. If you think one vlass with the original code as-is would be better at this stage, I can do that. 

The interface has the benefit of giving us extensibility in the future, but maybe that’s getting too far ahead. 

I explicitly chose _not_ to extract the common code from the two classes, or to make any other improvements/enhancements, keeping in the spirit if characterization testing.

**Comment by CarwynNelson** [comment]
I can see your reasoning behind moving out into separate classes - but I do feel that is maybe a step too far for characterisation tests if it can be avoided - which I do feel it can be in this case.

I'm not seeing how moving this logic into classes has made it more accessible in isolation - but maybe I'm missing something obvious here?

In terms of the filesystem - you should be able to easily mock that using `mikey179/vfsStream` which is already included in the project.

This is all assuming I'm not missing something glaring here?

**Comment by CarwynNelson** [comment]
Just to clarify - I think you new code you have written is much nicer and cleaner than the original Moodle code - even if it is light touch. I just feel that it is a bigger change than is needed to satisfy a characterisation test.

After there is a characterisation test in the repo for this functionality I think it would then make sense to do these abstractions.

The way I see it is:
* there would be characterisation tests against the `debug_backtrace` function that would document what it currently does.
* that would get merged in and would serve as a form of protection from us breaking backwards compat
* a new `DebugBacktrace` component would be written with its own unit tests and then `debug_backtrace` would be made to call the new component
* if any `debug_backtrace` characterisation tests fail then we know we have broken something and we need to make the decision around if that is okay
* eventually `debug_backtrace` can be removed with direct calls to the new component

This is how I am visualising things anyways...

**Comment by mistermuckle** [comment]
I will move the code into a single class so it will match the original function.

**Comment by mistermuckle** [comment]
The logic of the original function has been restored.

**Comment by mistermuckle** [comment]
Looks like I’ve got an extra file in there...

**Comment by mistermuckle** [comment]
...and it’s gone.

**Pull request merged**
