### PR TITLE
Replace adodb

### PR DESCRIPTION
**Pull request by JHeimbach**
replaced the custom adodb lib with a [fork](https://github.com/BetterMood/ADOdb). Will be loaded over composer.

Note, i did not replace the paths of the library with a autoloader.

### CODE REVIEW

**Comment by mistermuckle** [comment]
Is dev-better-mood already tagged in the forked lib?

**Comment by CarwynNelson** [comment]
```
Note, i did not replace the paths of the library with a autoloader.
```

Is this because it wouldn't been much more effort than it was worth? It looks to be the case - but just wanted to confirm.

**Comment by JHeimbach** [comment]
@mistermuckle its a branch in the fork, but we can tag it also.

@CarwynNelson yes

**Comment by JHeimbach** [comment]
just noticed that the folder lib/adodb was referenced in the ignore files and removed them

**Pull request merged**
