### PR TITLE
Move lib/htmlpurifier to composer

### LINKED ISSUE #18: Move lib/htmlpurifier to composer
* Moodle version is older than latest release (4.9.3)
* Moodle version modifies library

### PR DESCRIPTION
**Pull request by JHeimbach**
Fixes #18 

Moodle creates some extra classes for this library that I extracted in single files.(see lib/htmlpurifier/URIScheme) 
In order to autoload these (because they are needed inside of htmlpurifier) i added these as to the files to composer autoloader. They needed in the global namespace, thats why they are loaded manually. i dont know if there is a better/cleaner solution.

### CODE REVIEW

**Comment by CarwynNelson** [comment]
Please could you merge master into this branch?

It should make the build go green.

**Comment by CarwynNelson** [comment]
Looks good to me.

**Comment by CarwynNelson** [comment]
I've had a quick look at why they are in the global namespace (the library loads them based off convention).

We could move them into their own namespace and then class alias them so that the library can load them - but considering that they are only used for configuring this library i could take it either way.

I think we should get this merged.

**Comment by JHeimbach** [comment]
@CarwynNelson at the moment I don't know exactly how this lib is used, thats why i only changed it so the current workflow is not broken. But I agree, we should move these classes at some point in a namespace.

**Comment by mistermuckle** [comment]
I am not seeing where the custom classes are being used by Moodle. Are the classnames being built fromURI components or something?

**Comment by JHeimbach** [comment]
They are use for [here](https://github.com/ezyang/htmlpurifier/blob/1ef4375dbb7b14d9879088387ebef327f179d32b/library/HTMLPurifier/URISchemeRegistry.php#L62) in the htmlpurifier.

In moodle it is called [here](https://github.com/BetterMood/better-mood/blob/master/lib/weblib.php#L1798) there are allowedSchemas set, some of them are represented trough the custom classes

**Comment by mistermuckle** [comment]
Shouldn’t a PSR-0 rule like `"HTMLPurifier\\": "src/HTMLPurifier/"` be sufficient to get the autoloaded by the HTMLPurifier library?

**Comment by CarwynNelson** [comment]
@mistermuckle Unfortunately the htmlpurifier library loads these overrides based on convention and so they have to have this naming format.

[for reference see this function](https://github.com/BetterMood/better-mood/blob/master/lib/htmlpurifier/HTMLPurifier/URISchemeRegistry.php#L41). The important bits being:

```php
$class = 'HTMLPurifier_URIScheme_' . $scheme;
if (!class_exists($class)) {
    return;
}
$this->schemes[$scheme] = new $class();
return $this->schemes[$scheme];
```

**Comment by CarwynNelson** [comment]
@JHeimbach Could you resolve the conflicts please?

I think this would be good to merge then.

**Comment by JHeimbach** [comment]
@CarwynNelson done

**Pull request merged**
